name: Bug Report
description: Signaler un bug dans l'application
title: "[BUG]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir ce formulaire avec le maximum de détails pour nous aider à résoudre le problème rapidement.
        
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Description claire et concise du problème
      placeholder: Le bug se produit quand...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes de reproduction
      description: Comment reproduire le comportement
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire '...'
        4. Voir l'erreur
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Ce qui devrait se passer
      placeholder: Le comportement attendu est...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Ce qui se passe réellement
      placeholder: Au lieu de cela, je vois...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: OS, Python version, navigateur, etc.
      placeholder: |
        - OS: Linux Debian 12
        - Python: 3.11
        - Browser: Chrome 120 (si frontend)
        - Version app: 2.0.0
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Logs / Erreurs
      description: Messages d'erreur, logs applicatifs, stack traces
      placeholder: |
        ```
        Traceback (most recent call last):
        ...
        ```
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      description: À quel point ce bug est critique?
      options:
        - Critique (bloque complètement)
        - Haute (affecte fonctionnalité principale)
        - Moyenne (affecte fonctionnalité secondaire)
        - Basse (cosmétique ou mineur)
    validations:
      required: true

