name: Feature Request
description: Proposer une nouvelle fonctionnalité
title: "[FEATURE]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Merci de décrire la fonctionnalité que vous souhaitez voir ajoutée.
        
  - type: textarea
    id: problem
    attributes:
      label: Problème ou besoin
      description: Quel problème cette fonctionnalité résout-elle?
      placeholder: Je rencontre le problème suivant...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Comment cette fonctionnalité devrait fonctionner?
      placeholder: Je propose que...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: Avez-vous envisagé d'autres solutions?
      placeholder: J'ai aussi pensé à...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priorité MoSCoW
      description: Priorité selon MoSCoW
      options:
        - Must Have (Critique)
        - Should Have (Important)
        - Could Have (Souhaitable)
        - Won't Have (Hors scope)
    validations:
      required: true
      
  - type: textarea
    id: prd
    attributes:
      label: PRD associé
      description: Relier à un PRD existant ou nouveau
      placeholder: PRD-XXX ou Nouveau PRD
    validations:
      required: false

